//go:build ignore

package main

import (
	"bufio"
	"fmt"
	"io"
	"net/http"
	"os"
	"regexp"
	"sort"
	"strings"
	"time"
)

// Known GPU vendors we care about (MSI Afterburner supported)
// Note: pci.ids uses lowercase hex IDs
var knownVendors = map[string]string{
	"10de": "NVIDIA",
	"1002": "AMD",
	"8086": "Intel",
}

// Manufacturer codes supported by MSI Afterburner
var manufacturerCodes = map[string]string{
	"1043": "ASUS",
	"1462": "MSI",
	"10DE": "NVIDIA (Founders Edition)",
	"3842": "EVGA",
	"1458": "Gigabyte",
	"196E": "Gainward",
	"2592": "Zotac",
	"174B": "Sapphire",
	"1787": "PowerColor",
	"148C": "XFX",
	"1682": "PNY",
	"1971": "Palit",
	"1ACC": "Colorful",
	"1B4C": "Galax/KFA2",
	"1028": "Dell",
	"103C": "HP",
	"17AA": "Lenovo",
}

func main() {
	fmt.Println("Fetching pci.ids from online source...")

	// Fetch pci.ids file
	resp, err := http.Get("https://pci-ids.ucw.cz/v2.2/pci.ids")
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error fetching pci.ids: %v\n", err)
		os.Exit(1)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		fmt.Fprintf(os.Stderr, "Failed to fetch pci.ids: HTTP %d\n", resp.StatusCode)
		os.Exit(1)
	}

	// Parse the file
	vendors, devices := parsePCIIDs(resp.Body)

	// Filter to only known GPU vendors
	gpuCatalog := make(map[string]struct {
		Vendor string
		GPU    string
	})

	for vendorID := range vendors {
		if _, known := knownVendors[vendorID]; !known {
			continue
		}

		for deviceID, deviceName := range devices[vendorID] {
			// Skip non-GPU devices (audio, USB, PCIe switches, etc.)
			if !isGPUDisplayDevice(deviceName) {
				continue
			}

			key := vendorID + "_" + deviceID
			gpuName := cleanGPUName(vendorID, deviceName)
			if gpuName != "" {
				gpuCatalog[key] = struct {
					Vendor string
					GPU    string
				}{
					Vendor: knownVendors[vendorID],
					GPU:    gpuName,
				}
			}
		}
	}

	// Generate the Go file
	var sb strings.Builder

	sb.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	sb.WriteString(fmt.Sprintf("// Generated at: %s\n", time.Now().Format(time.RFC3339)))
	sb.WriteString("// Source: https://pci-ids.ucw.cz/v2.2/pci.ids\n")
	sb.WriteString("// This file contains auto-generated GPU and manufacturer data.\n")
	sb.WriteString("// To regenerate, run: go generate ./...\n\n")
	sb.WriteString("package catalog\n\n")

	// Write GPU catalog
	sb.WriteString("// gpuCatalog maps \"VendorID_DeviceID\" to human-readable GPU names.\n")
	sb.WriteString("// Source: pci.ids, filtered for MSI Afterburner supported vendors (NVIDIA, AMD, Intel).\n")
	sb.WriteString("var gpuCatalog = map[string]struct {\n")
	sb.WriteString("\tVendor string\n")
	sb.WriteString("\tGPU    string\n")
	sb.WriteString("}{\n")

	// Sort keys for consistent output
	keys := make([]string, 0, len(gpuCatalog))
	for k := range gpuCatalog {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for _, key := range keys {
		entry := gpuCatalog[key]
		fmt.Fprintf(&sb, "\t\"%s\": {Vendor: \"%s\", GPU: \"%s\"},\n", key, entry.Vendor, entry.GPU)
	}
	sb.WriteString("}\n\n")

	// Write manufacturer codes
	sb.WriteString("// manufacturerCodes maps SubsystemID vendor portion to manufacturer name.\n")
	sb.WriteString("// The SubsystemID format is: BBBBVVVV where BBBB = board/partner code, VVVV = vendor ID.\n")
	sb.WriteString("// We match on the vendor portion (last 4 hex digits).\n")
	sb.WriteString("// These are the manufacturers supported by MSI Afterburner.\n")
	sb.WriteString("var manufacturerCodes = map[string]string{\n")

	// Sort manufacturer keys for consistent output
	mfgKeys := make([]string, 0, len(manufacturerCodes))
	for k := range manufacturerCodes {
		mfgKeys = append(mfgKeys, k)
	}
	sort.Strings(mfgKeys)

	for _, key := range mfgKeys {
		fmt.Fprintf(&sb, "\t\"%s\": \"%s\",\n", key, manufacturerCodes[key])
	}
	sb.WriteString("}\n")

	// Write the generated file (relative to where go generate is invoked)
	err = os.WriteFile("catalog_generated.go", []byte(sb.String()), 0644)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error writing catalog_generated.go: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Successfully generated overclocking/msiaf/catalog/catalog_generated.go with %d GPU entries\n", len(gpuCatalog))
}

// parsePCIIDs reads the pci.ids file and extracts vendors and devices
func parsePCIIDs(r io.Reader) (map[string]string, map[string]map[string]string) {
	vendors := make(map[string]string)
	devices := make(map[string]map[string]string)

	scanner := bufio.NewScanner(r)
	var currentVendor string

	// Regex patterns
	vendorRegex := regexp.MustCompile(`^([0-9a-fA-F]{4})\s+(.+)$`)
	deviceRegex := regexp.MustCompile(`^\t([0-9a-fA-F]{4})\s+(.+)$`)

	for scanner.Scan() {
		line := scanner.Text()

		// Skip comments and empty lines
		if strings.HasPrefix(line, "#") || strings.TrimSpace(line) == "" {
			continue
		}

		// Check for vendor line (no leading tab)
		if !strings.HasPrefix(line, "\t") && !strings.HasPrefix(line, "\t\t") {
			if matches := vendorRegex.FindStringSubmatch(line); matches != nil {
				currentVendor = matches[1]
				vendors[currentVendor] = matches[2]
			}
		} else if strings.HasPrefix(line, "\t") && !strings.HasPrefix(line, "\t\t") {
			// Device line (single tab indent)
			if currentVendor != "" {
				if matches := deviceRegex.FindStringSubmatch(line); matches != nil {
					if devices[currentVendor] == nil {
						devices[currentVendor] = make(map[string]string)
					}
					devices[currentVendor][matches[1]] = matches[2]
				}
			}
		}
	}

	return vendors, devices
}

// isGPUDisplayDevice checks if a device name suggests it's a GPU/display device
// Returns false for audio devices, USB controllers, PCIe switches, etc.
func isGPUDisplayDevice(name string) bool {
	name = strings.ToLower(name)

	// Skip obvious non-GPU devices
	skipPatterns := []string{
		"audio",
		"usb",
		"ethernet",
		"network",
		"serial",
		"ide",
		"sata",
		"nvme",
		"bridge",
		"switch",
		"port",
		"upstream",
		"downstream",
		"cryptographic",
		"dummy",
		"absent",
		"hdmi",
		"dp ", // DisplayPort audio
		"i2c",
		"smbus",
		"thunderbolt",
	}

	for _, pattern := range skipPatterns {
		if strings.Contains(name, pattern) {
			return false
		}
	}

	// Keep devices that mention GPU-related terms
	keepPatterns := []string{
		"radeon",
		"geforce",
		"quadro",
		"tesla",
		"arc ",
		"iris",
		"graphics",
		"vga",
		"3d",
		"render",
		"firegl",
		"firemv",
		"firepro",
		"instinct",
		"mobility",
		"hd ",
		"uhd",
		"xe ",
		"dg2",
	}

	for _, pattern := range keepPatterns {
		if strings.Contains(name, pattern) {
			return true
		}
	}

	// If it doesn't match keep patterns but also doesn't match skip patterns,
	// be conservative and skip it
	return false
}

// cleanGPUName cleans up and normalizes GPU names from pci.ids
// It applies vendor-specific formatting rules for better readability
func cleanGPUName(vendorID, name string) string {
	// Common cleanup operations
	name = strings.TrimSpace(name)

	// Remove common redundant terms
	redundantTerms := []string{
		"Corporation",
		"Co., Ltd.",
		"Inc.",
		"Graphics",
		"Controller",
		"Display",
		"Adapter",
		"GPU",
		"Video",
		"Processor",
		"Chipset",
		"[",
		"]",
	}

	for _, term := range redundantTerms {
		name = strings.ReplaceAll(name, term, "")
	}

	// Clean up multiple spaces
	name = regexp.MustCompile(`\s+`).ReplaceAllString(name, " ")
	name = strings.TrimSpace(name)

	// Remove trailing punctuation
	name = strings.TrimRight(name, ":;,.-")

	// Vendor-specific formatting (pci.ids uses lowercase hex IDs)
	switch vendorID {
	case "10de": // NVIDIA
		// NVIDIA already has good naming in pci.ids, just clean it up
		name = formatNVIDIAName(name)
	case "1002": // AMD
		// AMD naming cleanup
		name = formatAMDName(name)
	case "8086": // Intel
		// Intel naming cleanup
		name = formatIntelName(name)
	}

	return name
}

// formatNVIDIAName applies NVIDIA-specific name formatting
func formatNVIDIAName(name string) string {
	// Remove chip codenames (AD102, AD103, AD104, GB202, etc.)
	// These are internal NVIDIA codenames that aren't user-friendly
	// Examples: "AD102 GeForce RTX 4090", "AD103M / GN21-X11 GeForce RTX 4090 Laptop"

	// Simple approach: remove first word if it's a codename
	words := strings.Fields(name)
	if len(words) > 0 {
		firstWord := words[0]
		// Check if first word is a codename (letters + numbers pattern, with optional suffix)
		// Patterns: AD104, GB202, TU117GLM, TU116BM, etc.
		if regexp.MustCompile(`^[A-Z]{2,3}\d+[A-Z]{0,3}$`).MatchString(firstWord) {
			words = words[1:]
		}
		// If second word is "/", remove it and the next word if it's also a codename
		if len(words) > 1 && words[0] == "/" {
			words = words[1:]
			if len(words) > 0 && regexp.MustCompile(`^[A-Z]{2,3}\d+[A-Z]{0,3}(-[A-Z0-9]+)?$`).MatchString(words[0]) {
				words = words[1:]
			}
		}
	}

	name = strings.Join(words, " ")
	return strings.TrimSpace(name)
}

// formatAMDName applies AMD-specific name formatting
func formatAMDName(name string) string {
	// Remove chip codenames (Navi 21, Navi 22, RDNA3, etc.)
	// These are internal AMD codenames that aren't user-friendly

	words := strings.Fields(name)
	cleanWords := make([]string, 0, len(words))

	skipNextNumber := false
	skipInitialCodename := true // Only skip RV/R patterns at the very start

	for i, word := range words {
		lowerWord := strings.ToLower(word)

		// Skip codename names and mark to skip next number
		if lowerWord == "navi" || lowerWord == "rdna" || lowerWord == "fiji" ||
			lowerWord == "arcturus" || lowerWord == "aldebaran" {
			skipNextNumber = true
			continue
		}

		// Skip the number after codename names
		if skipNextNumber && regexp.MustCompile(`^\d+$`).MatchString(word) {
			skipNextNumber = false
			continue
		}
		skipNextNumber = false

		// Skip RV###, R### patterns only at the very start (first 2 words)
		if skipInitialCodename && i < 2 && regexp.MustCompile(`^[Rr][Vv]?\d+$`).MatchString(word) {
			continue
		}
		if i > 0 {
			skipInitialCodename = false
		}

		// Skip professional suffixes like GL-XL, Pro-XTA, WKS-XM, etc.
		if regexp.MustCompile(`^(GL|Pro|WKS)-[A-Z]+$`).MatchString(word) {
			continue
		}

		cleanWords = append(cleanWords, word)
	}

	name = strings.Join(cleanWords, " ")
	return strings.TrimSpace(name)
}

// formatIntelName applies Intel-specific name formatting
func formatIntelName(name string) string {
	// Remove chip codenames (DG2, ATS-M, etc.) and codename lakes
	// These are internal Intel codenames that aren't user-friendly

	words := strings.Fields(name)
	cleanWords := make([]string, 0, len(words))

	// Track if we should skip the next "Lake" word and remove previous
	removeNextLake := false

	for i, word := range words {
		lowerWord := strings.ToLower(word)

		// Skip DG# patterns (e.g., DG2)
		if regexp.MustCompile(`^[Dd][Gg]\d+$`).MatchString(word) {
			continue
		}

		// Skip ATS-M
		if lowerWord == "ats-m" {
			continue
		}

		// Detect codename before "Lake" (e.g., "Panther" before "Lake")
		if i < len(words)-1 && strings.ToLower(words[i+1]) == "lake" {
			removeNextLake = true
			continue // Skip the codename word
		}

		// Skip "Lake" itself if we marked it for removal
		if removeNextLake && lowerWord == "lake" {
			removeNextLake = false
			continue
		}
		removeNextLake = false

		cleanWords = append(cleanWords, word)
	}

	name = strings.Join(cleanWords, " ")
	return strings.TrimSpace(name)
}
