//go:generate go run ../../../cmd/gencatalog/main.go

package catalog

import "strings"

// GPUInfo contains human-readable information about a GPU.
type GPUInfo struct {
	VendorName   string
	GPUName      string
	Manufacturer string
	IsKnown      bool
}

// gpuCatalog and manufacturerCodes are defined in catalog_generated.go
// They are auto-generated by running: go generate ./...

// LookupGPU returns human-readable GPU information based on VendorID and DeviceID.
// If the GPU is not in the catalog, it returns an GPUInfo with IsKnown=false.
func LookupGPU(vendorID, deviceID string) GPUInfo {
	// Normalize to lowercase since pci.ids uses lowercase hex IDs
	key := strings.ToLower(vendorID) + "_" + strings.ToLower(deviceID)

	if entry, ok := gpuCatalog[key]; ok {
		return GPUInfo{
			VendorName: entry.Vendor,
			GPUName:    entry.GPU,
			IsKnown:    true,
		}
	}

	// Return unknown GPU info with raw IDs for display
	return GPUInfo{
		VendorName: lookupVendorName(vendorID),
		GPUName:    "Unknown GPU (DEV_" + deviceID + ")",
		IsKnown:    false,
	}
}

// LookupManufacturer returns the manufacturer name from a SubsystemID.
// SubsystemID format: BBBBVVVV (BBBB = board code, VVVV = vendor ID).
// Returns "Unknown" if the vendor code is not recognized.
func LookupManufacturer(subsystemID string) string {
	if len(subsystemID) < 4 {
		return "Unknown"
	}

	// Extract vendor portion (last 4 hex digits)
	vendorCode := subsystemID[len(subsystemID)-4:]

	if manufacturer, ok := manufacturerCodes[vendorCode]; ok {
		return manufacturer
	}

	return "Unknown (VID_" + vendorCode + ")"
}

// lookupVendorName returns the vendor name from a VendorID.
func lookupVendorName(vendorID string) string {
	switch vendorID {
	case "10DE":
		return "NVIDIA"
	case "1002":
		return "AMD"
	case "8086":
		return "Intel"
	default:
		return "Unknown Vendor (VEN_" + vendorID + ")"
	}
}

// GetFullGPUDescription returns a complete human-readable GPU description.
// Format: "Manufacturer Vendor GPUName" (e.g., "ASUS NVIDIA GeForce RTX 5090")
func GetFullGPUDescription(vendorID, deviceID, subsystemID string) string {
	gpuInfo := LookupGPU(vendorID, deviceID)
	manufacturer := LookupManufacturer(subsystemID)

	return manufacturer + " " + gpuInfo.VendorName + " " + gpuInfo.GPUName
}
